
export const translatedInfo: Record<string, Record<string, string>> = {
    "Language": {
         "de": "Deutsch",
         "en": "English",
         "pl": "Polski",
         "es": "Español",
         "fr": "Français",
         "it": "Italiano",
         "cz": "Čeština",
         "pt": "Português",
         "hu": "Magyar",
         "nl": "Nederlands",
         "gr": "Ελληνικά",
         "ru": "Русский",
         "tr": "Türkçe",
         "ir": "فارسی"
    },
    "Welcome": {
       "de": "Willkommen",
       "en": "Welcome",
       "pl": "Witamy",
       "es": "Bienvenido",
       "fr": "Bienvenue",
       "it": "Benvenuto",
       "cz": "Vítejte",
       "pt": "Bem-vindo",
       "hu": "Üdvözöljük",
       "nl": "Velkommen",
       "gr": "Καλώς ήρθατε",
       "ru": "Добро пожаловать",
       "tr": "Hoşgeldiniz",
       "ir": "خوش آمدید"
    },
    "Footer-Info": {
        "de": "Scan Manager 2025 von R.Stolz",
        "en": "Scan Manager 2025 by R.Stolz",
        "pl": "Scan Manager 2025 autorstwa R.Stolz",
        "es": "Scan Manager 2025 por R.Stolz",
        "fr": "Scan Manager 2025 par R.Stolz",
        "it": "Scan Manager 2025 di R.Stolz",
        "cz": "Scan Manager 2025 od R.Stolz",
        "pt": "Scan Manager 2025 por R.Stolz",
        "hu": "Scan Manager 2025 R.Stolz által",
        "nl": "Scan Manager 2025 door R.Stolz",
        "gr": "Scan Manager 2025 από R.Stolz",
        "ru": "Scan Manager 2025 от R.Stolz",
        "tr": "R.Stolz tarafından Scan Manager 2025",
        "ir": "Scan Manager 2025 توسط R.Stolz"
    },
    "Login": {
        "de": "Mit Azure anmelden",
        "en": "Login with Azure",
        "pl": "Zaloguj się przez Azure",
        "es": "Iniciar sesión con Azure",
        "fr": "Se connecter avec Azure",
        "it": "Accedi con Azure",
        "cz": "Přihlásit se přes Azure",
        "pt": "Entrar com Azure",
        "hu": "Bejelentkezés Azure-val",
        "nl": "Inloggen met Azure",
        "gr": "Σύνδεση με το Azure",
        "ru": "Войти через Azure",
        "tr": "Azure ile giriş yap",
        "ir": "ورود با Azure"
    },
    "Logout": {
        "de": "Abmelden",
        "en": "Logout",
        "pl": "Wyloguj się",
        "es": "Cerrar sesión",
        "fr": "Se déconnecter",
        "it": "Disconnettersi",
        "cz": "Odhlásit se",
        "pt": "Sair",
        "hu": "Kijelentkezés",
        "nl": "Uitloggen",
        "gr": "Αποσύνδεση",
        "ru": "Выйти",
        "tr": "Çıkış yap",
        "ir": "خروج"
    },
    "Profile": {
        "de": "Profile",
        "en": "Profile",
        "pl": "Profil",
        "es": "Perfil",
        "fr": "Profil",
        "it": "Profilo",
        "cz": "Profil",
        "pt": "Perfil",
        "hu": "Profil",
        "nl": "Profiel",
        "gr": "Προφίλ",
        "ru": "Профиль",
        "tr": "Profil",
        "ir": "پروفایل"
    },
    "Customers": {
        "de": "Kunden",
        "en": "Customers",
        "pl": "Klienci",
        "es": "Clientes",
        "fr": "Clients",
        "it": "Clienti",
        "cz": "Zákazníci",
        "pt": "Clientes",
        "hu": "Ügyfelek",
        "nl": "Klanten",
        "gr": "Πελάτες",
        "ru": "Клиенты",
        "tr": "Müşteriler",
        "ir": "مشتریان"
    },
    "Service Partners": {
        "de": "Service Partner",
        "en": "Service Partners",
        "pl": "Partnerzy serwisowi",
        "es": "Socios de servicio",
        "fr": "Partenaires de service",
        "it": "Partner di servizio",
        "cz": "Servisní partneři",
        "pt": "Parceiros de serviço",
        "hu": "Szolgáltatói partnerek",
        "nl": "Servicepartners",
        "gr": "Συνεργάτες υπηρεσιών",
        "ru": "Сервисные партнеры",
        "tr": "Hizmet Ortakları",
        "ir": "شرکای خدماتی"
    },
    "Scanner": {
        "de": "Scanner",
        "en": "Scanner",
        "pl": "Skaner",
        "es": "Escáner",
        "fr": "Scanner",
        "it": "Scanner",
        "cz": "Skenner",
        "pt": "Scanner",
        "hu": "Szkenner",
        "nl": "Scanner",
        "gr": "Σαρωτής",
        "ru": "Сканер",
        "tr": "Tarayıcı",
        "ir": "اسکنر"
    },
    "name": {
        "de": "Name",
        "en": "Name",
        "pl": "Nazwa",
        "es": "Nombre",
        "fr": "Nom",
        "it": "Nome",
        "cz": "Jméno",
        "pt": "Nome",
        "hu": "Név",
        "nl": "Naam",
        "gr": "Όνομα",
        "ru": "Имя",
        "tr": "İsim",
        "ir": "نام"
    },
    "contactPerson":{
        "de": "Ansprechpartner",
        "en": "Contact Person",
        "pl": "Osoba kontaktowa",
        "es": "Persona de contacto",
        "fr": "Personne de contact",
        "it": "Persona di contatto",
        "cz": "Kontaktní osoba",
        "pt": "Pessoa de contato",
        "hu": "Kapcsolattartó személy",
        "nl": "Contactpersoon",
        "gr": "Υπεύθυνος επικοινωνίας",
        "ru": "Контактное лицо",
        "tr": "İletişim Kişisi",
        "ir": "شخص تماس"
    },
    "notes": {
        "de": "Notizen",
        "en": "Notes",
        "pl": "Notatki",
        "es": "Notas",
        "fr": "Notes",
        "it": "Note",
        "cz": "Poznámky",
        "pt": "Notas",
        "hu": "Jegyzetek",
        "nl": "Notities",
        "gr": "Σημειώσεις",
        "ru": "Заметки",
        "tr": "Notlar",
        "ir": "یادداشت‌ها"
    },
    "image": {
        "de": "Bild",
        "en": "Image",
        "pl": "Obraz",
        "es": "Imagen",
        "fr": "Image",
        "it": "Immagine",
        "cz": "Obrázek",
        "pt": "Imagem",
        "hu": "Kép",
        "nl": "Afbeelding",
        "gr": "Εικόνα",
        "ru": "Изображение",
        "tr": "Görüntü",
        "ir": "تصویر"
    },
    "sql-id": {
        "de": "SQL-ID",
        "en": "SQL-ID",
        "pl": "SQL-ID",
        "es": "SQL-ID",
        "fr": "SQL-ID",
        "it": "SQL-ID",
        "cz": "SQL-ID",
        "pt": "SQL-ID",
        "hu": "SQL-azonosító",
        "nl": "SQL-ID",
        "gr": "SQL-ταυτότητα",
        "ru": "SQL-ИД",
        "tr": "SQL-ID",
        "ir": "SQL-ID"
    },
    "Loading": {
        "de": "Laden",
        "en": "Loading",
        "pl": "Ładowanie",
        "es": "Cargando",
        "fr": "Chargement",
        "it": "Caricamento",
        "cz": "Načítání",
        "pt": "Carregando",
        "hu": "Betöltés",
        "nl": "Laden",
        "gr": "Φόρτωση",
        "ru": "Загрузка",
        "tr": "Yükleniyor",
        "ir": "در حال بارگذاری"
    },
    "modelName": {
        "de": "Modellname",
        "en": "Model Name",
        "pl": "Nazwa modelu",
        "es": "Nombre del modelo",
        "fr": "Nom du modèle",
        "it": "Nome del modello",
        "cz": "Název modelu",
        "pt": "Nome do modelo",
        "hu": "Modell neve",
        "nl": "Modelnaam",
        "gr": "Όνομα μοντέλου",
        "ru": "Название модели",
        "tr": "Model Adı",
        "ir": "نام مدل"
    },
    "serialNumber": {
        "de": "Seriennummer",
        "en": "Serial Number",
        "pl": "Numer seryjny",
        "es": "Número de serie",
        "fr": "Numéro de série",
        "it": "Numero di serie",
        "cz": "Sériové číslo",
        "pt": "Número de série",
        "hu": "Sorozatszám",
        "nl": "Serienummer",
        "gr": "Αριθμός σειράς",
        "ru": "Серийный номер",
        "tr": "Seri Numarası",
        "ir": "شماره سریال"
    },
    "contractNumber":{
        "de": "Vertragsnummer",
        "en": "Contract Number",
        "pl": "Numer umowy",
        "es": "Número de contrato",
        "fr": "Numéro de contrat",
        "it": "Numero di contratto",
        "cz": "Číslo smlouvy",
        "pt": "Número do contrato",
        "hu": "Szerződésszám",
        "nl": "Contractnummer",
        "gr": "Αριθμός σύμβασης",
        "ru": "Номер контракта",
        "tr": "Sözleşme Numarası",
        "ir": "شماره قرارداد"
    },
    "Invoice Number": {
        "de": "Rechnungsnummer",
        "en": "Invoice Number",
        "pl": "Numer faktury",
        "es": "Número de factura",
        "fr": "Numéro de facture",
        "it": "Numero di fattura",
        "cz": "Číslo faktury",
        "pt": "Número da fatura",
        "hu": "Számlaszám",
        "nl": "Factuurnummer",
        "gr": "Αριθμός τιμολογίου",
        "ru": "Номер счета",
        "tr": "Fatura Numarası",
        "ir": "شماره فاکتور"
    },
    "contractType":{
        "de": "Vertragsart",
        "en": "Contract Type",
        "pl": "Rodzaj umowy",
        "es": "Tipo de contrato",
        "fr": "Type de contrat",
        "it": "Tipo di contratto",
        "cz": "Typ smlouvy",
        "pt": "Tipo de contrato",
        "hu": "Szerződés típusa",
        "nl": "Contracttype",
        "gr": "Τύπος σύμβασης",
        "ru": "Тип контракта",
        "tr": "Sözleşme Türü",
        "ir": "نوع قرارداد"
    },
    "status": {
        "de": "Status",
        "en": "Status",
        "pl": "Status",
        "es": "Estado",
        "fr": "Statut",
        "it": "Stato",
        "cz": "Stav",
        "pt": "Estado",
        "hu": "Állapot",
        "nl": "Status",
        "gr": "Κατάσταση",
        "ru": "Статус",
        "tr": "Durum",
        "ir": "وضعیت"
    },
    "No Maintenance":{
        "de": "Keine Wartung",
        "en": "No Maintenance",
        "pl": "Brak konserwacji",
        "es": "Sin mantenimiento",
        "fr": "Pas de maintenance",
        "it": "Nessuna manutenzione",
        "cz": "Žádná údržba",
        "pt": "Sem manutenção",
        "hu": "Nincs karbantartás",
        "nl": "Geen onderhoud",
        "gr": "Χωρίς συντήρηση",
        "ru": "Нет обслуживания",
        "tr": "Bakım Yok",
        "ir": "بدون نگهداری"
    },
    "startDate": {
        "de": "Startdatum",
        "en": "Start Date",
        "pl": "Data rozpoczęcia",
        "es": "Fecha de inicio",
        "fr": "Date de début",
        "it": "Data di inizio",
        "cz": "Datum zahájení",
        "pt": "Data de início",
        "hu": "Kezdő dátum",
        "nl": "Startdatum",
        "gr": "Ημερομηνία έναρξης",
        "ru": "Дата начала",
        "tr": "Başlangıç Tarihi",
        "ir": "تاریخ شروع"
    },
    "endDate":{
        "de": "Enddatum",
        "en": "End Date",
        "pl": "Data zakończenia",
        "es": "Fecha de finalización",
        "fr": "Date de fin",
        "it": "Data di fine",
        "cz": "Datum ukončení",
        "pt": "Data de término",
        "hu": "Befejező dátum",
        "nl": "Einddatum",
        "gr": "Ημερομηνία λήξης",
        "ru": "Дата окончания",
        "tr": "Bitiş Tarihi",
        "ir": "تاریخ پایان"
    },
    "purchasePrice":{
        "de": "Kaufpreis",
        "en": "Purchase Price",
        "pl": "Cena zakupu",
        "es": "Precio de compra",
        "fr": "Prix d'achat",
        "it": "Prezzo di acquisto",
        "cz": "Kupní cena",
        "pt": "Preço de compra",
        "hu": "Vételár",
        "nl": "Aankoopprijs",
        "gr": "Τιμή αγοράς",
        "ru": "Цена покупки",
        "tr": "Satın Alma Fiyatı",
        "ir": "قیمت خرید"
    },
    "salePrice":{
        "de": "Verkaufspreis",
        "en": "Sale Price",
        "pl": "Cena sprzedaży",
        "es": "Precio de venta",
        "fr": "Prix de vente",
        "it": "Prezzo di vendita",
        "cz": "Prodejní cena",
        "pt": "Preço de venda",
        "hu": "Eladási ár",
        "nl": "Verkoopprijs",
        "gr": "Τιμή πώλησης",
        "ru": "Цена продажи",
        "tr": "Satış Fiyatı",
        "ir": "قیمت فروش"
    },
    "depreciation": {
        "de": "Abschreibung",
        "en": "Depreciation",
        "pl": "Amortyzacja",
        "es": "Depreciación",
        "fr": "Amortissement",
        "it": "Ammortamento",
        "cz": "Odpis",
        "pt": "Depreciação",
        "hu": "Értékcsökkenés",
        "nl": "Afschrijving",
        "gr": "Αποσβέσεις",
        "ru": "Амортизация",
        "tr": "Amortisman",
        "ir": "استهلاک"
    },
    "customerID":{
        "de": "Kunden-ID",
        "en": "Customer ID",
        "pl": "ID klienta",
        "es": "ID del cliente",
        "fr": "ID du client",
        "it": "ID cliente",
        "cz": "ID zákazníka",
        "pt": "ID do cliente",
        "hu": "Ügyfél azonosító",
        "nl": "Klant-ID",
        "gr": "Ταυτότητα πελάτη",
        "ru": "Идентификатор клиента",
        "tr": "Müşteri Kimliği",
        "ir": "شناسه مشتری"
    },
    "servicePartnerId": {
        "de": "Service Partner ID",
        "en": "Service Partner ID",
        "pl": "ID partnera serwisowego",
        "es": "ID del socio de servicio",
        "fr": "ID du partenaire de service",
        "it": "ID partner di servizio",
        "cz": "ID servisního partnera",
        "pt": "ID do parceiro de serviço",
        "hu": "Szolgáltatói partner azonosító",
        "nl": "Servicepartner-ID",
        "gr": "Ταυτότητα συνεργάτη υπηρεσιών",
        "ru": "Идентификатор сервисного партнера",
        "tr": "Hizmet Ortağı Kimliği",
        "ir": "شناسه شریک خدمات"
    },
    "Maintenance Content":{
        "de": "Wartungsinhalt",
        "en": "Maintenance Content",
        "pl": "Zawartość konserwacji",
        "es": "Contenido de mantenimiento",
        "fr": "Contenu de maintenance",
        "it": "Contenuto della manutenzione",
        "cz": "Obsah údržby",
        "pt": "Conteúdo de manutenção",
        "hu": "Karbantartási tartalom",
        "nl": "Onderhoudsinhoud",
        "gr": "Περιεχόμενο συντήρησης",
        "ru": "Содержание обслуживания",
        "tr": "Bakım İçeriği",
        "ir": "محتوای نگهداری"
    },
    "Yes": {
        "de": "Ja",
        "en": "Yes",
        "pl": "Tak",
        "es": "Sí",
        "fr": "Oui",
        "it": "Sì",
        "cz": "Ano",
        "pt": "Sim",
        "hu": "Igen",
        "nl": "Ja",
        "gr": "Ναι",
        "ru": "Да",
        "tr": "Evet",
        "ir": "بله"
    },
    "No": {
        "de": "Nein",
        "en": "No",
        "pl": "Nie",
        "es": "No",
        "fr": "Non",
        "it": "No",
        "cz": "Ne",
        "pt": "Não",
        "hu": "Nem",
        "nl": "Nee",
        "gr": "Όχι",
        "ru": "Нет",
        "tr": "Hayır",
        "ir": "خیر"
    },
    "deviceType": {
        "de": "Gerätetyp",
        "en": "Device Type",
        "pl": "Typ urządzenia",
        "es": "Tipo de dispositivo",
        "fr": "Type d'appareil",
        "it": "Tipo di dispositivo",
        "cz": "Typ zařízení",
        "pt": "Tipo de dispositivo",
        "hu": "Eszköz típusa",
        "nl": "Apparaattype",
        "gr": "Τύπος συσκευής",
        "ru": "Тип устройства",
        "tr": "Cihaz Türü",
        "ir": "نوع دستگاه"
    },
    "debitorNrNavision": {
        "de": "Debitor Nr. Navision",
        "en": "Debtor Number Navision",
        "pl": "Nr Dłużnika Navision",
        "es": "Núm. Deudor Navision",
        "fr": "N° Débiteur Navision",
        "it": "Num. Debitore Navision",
        "cz": "Číslo Dlužníka Navision",
        "pt": "Núm. Devedor Navision",
        "hu": "Adós szám Navision",
        "nl": "Debiteur Nr. Navision",
        "gr": "Αρ. Χρεώστη Navision",
        "ru": "Номер дебитора Navision",
        "tr": "Borçlu No. Navision",
        "ir": "شماره بدهکار Navision"
    },
    "contactDetails": {
        "de": "Kontaktdaten",
        "en": "Contact Details",
        "pl": "Dane kontaktowe",
        "es": "Detalles de contacto",
        "fr": "Coordonnées",
        "it": "Dettagli di contatto",
        "cz": "Kontaktní údaje",
        "pt": "Detalhes de contato",
        "hu": "Kapcsolattartási adatok",
        "nl": "Contactgegevens",
        "gr": "Στοιχεία επικοινωνίας",
        "ru": "Контактные данные",
        "tr": "İletişim Detayları",
        "ir": "جزئیات تماس"
    },
    "isArchived": {
        "de": "Ist archiviert",
        "en": "Is Archived",
        "pl": "Jest zarchiwizowane",
        "es": "Está archivado",
        "fr": "Est archivé",
        "it": "È archiviato",
        "cz": "Je archivováno",
        "pt": "Está arquivado",
        "hu": "Archiválva",
        "nl": "Is gearchiveerd",
        "gr": "Αρχειοθετήθηκε",
        "ru": "Архивировано",
        "tr": "Arşivlendi",
        "ir": "بایگانی شده است"
    },
    "creditorNrNavision": {
        "de": "Kreditor Nr. Navision",
        "en": "Creditor Number Navision",
        "pl": "Nr Wierzyciela Navision",
        "es": "Núm. Acreedor Navision",
        "fr": "N° Créancier Navision",
        "it": "Num. Creditore Navision",
        "cz": "Číslo Věřitele Navision",
        "pt": "Núm. Credor Navision",
        "hu": "Hitelező szám Navision",
        "nl": "Crediteur Nr. Navision",
        "gr": "Αρ. Πιστωτή Navision",
        "ru": "Номер кредитора Navision",
        "tr": "Alacaklı No. Navision",
        "ir": "شماره بستانکار Navision"
    },
    "manufacturerCode": {
        "de": "Hersteller Code",
        "en": "Manufacturer Code",
        "pl": "Kod producenta",
        "es": "Código del fabricante",
        "fr": "Code du fabricant",
        "it": "Codice del produttore",
        "cz": "Kód výrobce",
        "pt": "Código do fabricante",
        "hu": "Gyártói kód",
        "nl": "Fabrikantcode",
        "gr": "Κωδικός κατασκευαστή",
        "ru": "Код производителя",
        "tr": "Üretici Kodu",
        "ir": "کد سازنده"
    },
    "scannerNrNavision": {
        "de": "Scanner Nr. Navision",
        "en": "Scanner Number Navision",
        "pl": "Nr Skanera Navision",
        "es": "Núm. Escáner Navision",
        "fr": "N° Scanner Navision",
        "it": "Num. Scanner Navision",
        "cz": "Číslo skeneru Navision",
        "pt": "Núm. Scanner Navision",
        "hu": "Szkenner szám Navision",
        "nl": "Scanner Nr. Navision",
        "gr": "Αρ. Σαρωτή Navision",
        "ru": "Номер сканера Navision",
        "tr": "Tarayıcı No. Navision",
        "ir": "شماره اسکنر Navision"
    },
    "slaMaintenance": {
        "de": "SLA Wartung",
        "en": "SLA Maintenance",
        "pl": "Konserwacja SLA",
        "es": "Mantenimiento SLA",
        "fr": "Maintenance SLA",
        "it": "Manutenzione SLA",
        "cz": "Údržba SLA",
        "pt": "Manutenção SLA",
        "hu": "SLA karbantartás",
        "nl": "SLA-onderhoud",
        "gr": "Συντήρηση SLA",
        "ru": "Обслуживание по SLA",
        "tr": "SLA Bakımı",
        "ir": "نگهداری SLA"
    },
    "locationAddress": {
        "de": "Standort Adresse",
        "en": "Location Address",
        "pl": "Adres lokalizacji",
        "es": "Dirección de la ubicación",
        "fr": "Adresse du lieu",
        "it": "Indirizzo della sede",
        "cz": "Adresa umístění",
        "pt": "Endereço do local",
        "hu": "Helyszín címe",
        "nl": "Locatieadres",
        "gr": "Διεύθυνση τοποθεσίας",
        "ru": "Адрес местоположения",
        "tr": "Konum Adresi",
        "ir": "آدرس مکان"
    },
    "contactPersonDetails": {
        "de": "Ansprechpartner Details",
        "en": "Contact Person Details",
        "pl": "Szczegóły osoby kontaktowej",
        "es": "Detalles de la persona de contacto",
        "fr": "Détails de la personne de contact",
        "it": "Dettagli della persona di contatto",
        "cz": "Podrobnosti o kontaktní osobě",
        "pt": "Detalhes da pessoa de contato",
        "hu": "Kapcsolattartó személy részletei",
        "nl": "Contactpersoon details",
        "gr": "Λεπτομέρειες υπεύθυνου επικοινωνίας",
        "ru": "Данные контактного лица",
        "tr": "İletişim Kişisi Detayları",
        "ir": "جزئیات شخص تماس"
    },
    "acquisitionDate": {
        "de": "Anschaffungsdatum",
        "en": "Acquisition Date",
        "pl": "Data nabycia",
        "es": "Fecha de adquisición",
        "fr": "Date d'acquisition",
        "it": "Data di acquisizione",
        "cz": "Datum pořízení",
        "pt": "Data de aquisição",
        "hu": "Beszerzés dátuma",
        "nl": "Aankoopdatum",
        "gr": "Ημερομηνία απόκτησης",
        "ru": "Дата приобретения",
        "tr": "Edinme Tarihi",
        "ir": "تاریخ اکتساب"
    },
    "purchasedBy": {
        "de": "Gekauft von",
        "en": "Purchased By",
        "pl": "Zakupione przez",
        "es": "Comprado por",
        "fr": "Acheté par",
        "it": "Acquistato da",
        "cz": "Zakoupeno kým",
        "pt": "Comprado por",
        "hu": "Vásárolta",
        "nl": "Gekocht door",
        "gr": "Αγοράστηκε από",
        "ru": "Куплено у",
        "tr": "Tarafından satın alındı",
        "ir": "خریداری شده توسط"
    }
}