spring:
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope: openid, profile, email
            redirect-uri: "http://localhost:8080/login/oauth2/code/azure"
            client-name: Azure
            authorization-grant-type: authorization_code
        provider:
          azure:
            issuer-uri: https://login.microsoftonline.com/${TENANT_ID}/v2.0


#spring:
#  cloud:
#    azure:
#      active-directory:
#        enabled: true
#        profile:
#          tenant-id: ${TENANT_ID}
#        credential:
#          client-id: ${CLIENT_ID}
#          client-secret: ${CLIENT_SECRET}