spring.application.name=backend

CLOUDINARY_URL=${CLOUDINARY_URL}
spring.servlet.multipart.max-file-size=5MB

# PostgreSQL Datenbankverbindung
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Einstellungen für PostgreSQL
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# PostgreSQL spezifische Einstellungen
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.format_sql=true
